# docker-compose.prod.yml  
# Production configuration overrides
version: '3.8'

services:
  backend:
    build:
      target: production
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    build:
      target: production
    environment:
      NODE_ENV: production
      GENERATE_SOURCEMAP: false
    restart: always

  # Enable nginx in production
  nginx:
    profiles: []

  # Disable development tools in production
  adminer:
    profiles:
      - never-run